### ISSUE TITLE
useNavigationComponentDidAppear not working when mixed with react-native-safe-area-context's SafeAreaProvider

### ISSUE THREAD

**Issue by benpeke** [underscopeio/react-native-navigation-hooks#54] opened 2021-01-28 22:37 UTC
Working with both RNN hooks and SafeAreaProvider breaks the useNavigationComponentDidAppear hook.

```
Navigation.registerComponent(
      componentName,
      () => (props: any): React.ReactElement<any> => (
        <SafeAreaProvider>
            <NavigationProvider value={{ componentId: props.componentId }}>
                <Component {...props} />
            </NavigationProvider>
        <SafeAreaProvider>
      ),
      () => Component
);
```

And in the Component useNavigationComponentDidAppear is never called. Verified by adding log statements to Navigation.events().registerComponentDidAppearListener. In the logs I can only see the output from registerComponentDidAppearListener however useNavigationComponentDidAppear never shows any logs for certain components.

**Comment by jpgarcia** [comment] 2021-01-30 21:20
Hi @benpeke thank you for reporting this but unfortunately I couldn't reproduce the issue and it's actually working:

![image](https://user-images.githubusercontent.com/95109/106368363-c4b4f500-6327-11eb-8cad-cf5c7c97c120.png)

This is how I'm registering the component as you mention

```ts
Navigation.registerComponent(
  'WelcomeScreen',
  () => props => (
    <SafeAreaProvider>
      <NavigationProvider value={{ componentId: props.componentId }}>
        <WelcomeScreen {...props} />
      </NavigationProvider>
    </SafeAreaProvider>
  ),
  () => WelcomeScreen
)
```

and that's how I'm using it inside the actual screen:


```tsx
import React from 'react'
import { Text } from 'react-native'
import { NavigationFunctionComponent } from 'react-native-navigation'
import { useNavigationComponentDidAppear } from 'react-native-navigation-hooks'

const WelcomeScreen: NavigationFunctionComponent = () => {
  useNavigationComponentDidAppear(() => {
    console.warn('component did appeared')
  })

  return <Text>WelcomeScreen</Text>
}

export default WelcomeScreen
```

I'm going to close this issue for now. If you are still facing it please try with a project from scratch and if it doesn't not work publish it as a public repo so we can troubleshoot it.

**Closed by jpgarcia** 2021-01-30 21:20 UTC

**Comment by yadigarbz** [comment] 2022-06-18 21:31
This issue is definitely valid

Basic information:

Provider Wrapper
```
export const ComponentSetupWrapper: (
  Component: NavigationFunctionComponent,
) => (props: any) => ReactElement = Component => {
  return props => (
    <SafeAreaProvider>
      <NavigationProvider value={{componentId: props.componentId}}>
        <AuthorizationProvider>
          <Component {...props} />
        </AuthorizationProvider>
      </NavigationProvider>
    </SafeAreaProvider>
  );
};
```

Landing Page Listener
```
export const LandingPage: NavigationFunctionComponent = ({componentId}) => {
  useNavigationComponentDidAppear(() => {
    initializeDevice()
      .then(hasSession => {
        if (hasSession) {
          Navigation.setRoot(AppStackRoot);
        } else {
          Navigation.setRoot(AuthStackRoot);
        }
      })
      .catch(console.error);
  }, componentId);

  const {user, accessToken, device} = useAuthorizationState();
  const {initializeDevice} = useAuthorizationActions();

  useEffect(() => {}, [user, device, accessToken]);
```

Versions:
"react-native-navigation": "^7.28.0",
"react-native-navigation-hooks": "^6.3.0",
"react-native-safe-area-context": "^4.3.1",
