### ISSUE TITLE
useNavigationComponentDidAppear not firing on root component

### ISSUE THREAD

**Issue by daveyjones** [underscopeio/react-native-navigation-hooks#51] opened 2021-01-25 21:19 UTC
Great library! I'm just having one issue. Given the following setup, `useNavigationComponentDidAppear` is not firing when the app starts up. It works in all other cases. Is this a bug or am I doing something wrong?

_Edited: I fixed a few typos in the code below._

**index.js**
```
Navigation.registerComponent("Landing", () => require("./Landing.js"))

Navigation.events().registerAppLaunchedListener(async () => {
  Navigation.setRoot({
    root: {
      stack: {
        children: [{component: {name: "Landing"}}]
      }
    }
  })
})
```

**Landing.js**
```
...

function Landing(props) {

  useNavigationComponentDidAppear(async event => {
    console.warn("I never get called...")
  }, {componentId: props.componentId})

}
```

**Comment by jpgarcia** [comment] 2021-01-30 21:25
Hi @daveyjones sorry but I could not reproduce the issue. It seems pretty similar to https://github.com/underscopeio/react-native-navigation-hooks/issues/54

Which versions of RNN and RNN-Hooks you are using?

Could you please provide us a clean public Github repo with a basic source code so yo can have a clear path to troubleshoot the issue. 

Closing this for now.

**Closed by jpgarcia** 2021-01-30 21:25 UTC

**Comment by TimP4w** [comment] 2021-06-14 08:35
@jpgarcia This works on iOS but not on Android.
